### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by kanato-masayoshi** [hotchemi/zaim.js#2]
I want to rewrite the whole code in Typescript, which is, as you may know, a Javascript-compatible static typing language.  
Of course, users who only use Javascript are not affected. Rewriting the code in Typescript just means adding kind type support for those who prefer to write their code in Typescript.  
What do you think about this?

**Comment by kanato-masayoshi** [comment]
@hotchemi I would like to hear your opinion.

**Comment by hotchemi** [comment]
Yea I'm a huge fun of TS! Go go!

**Comment by kanato-masayoshi** [comment]
Good. I will work on it. 👍
